# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DE_Rcpp <- function(expr_norm_1, expr_norm_2, log_scores, ind_A, lib_size_1, lib_size_2) {
    .Call(`_bigSCale_DE_Rcpp`, expr_norm_1, expr_norm_2, log_scores, ind_A, lib_size_1, lib_size_2)
}

C_compute_distances <- function(expr_driving_norm, log_scores, ind_A, lib_size) {
    .Call(`_bigSCale_C_compute_distances`, expr_driving_norm, log_scores, ind_A, lib_size)
}

rcpp_hello_world <- function() {
    .Call(`_bigSCale_rcpp_hello_world`)
}

